"""
This is a setup.py script generated by py2applet

build:
python3 setup.py py2app -A

lauch: 
./dist/Tomado.app/Contents/MacOS/Tomado

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Tomado.py']
DATA_FILES = ["icons"]
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'LSUIElement': True,
    },
    'packages': ['rumps'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
